config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations",
                                       :omniauth_callbacks => "users/omniauth_callbacks"}
  #devise_for :users


  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #get ('/login') => redirect(:login) 
  get ("/") => redirect("users")
  
  get "/home" => "users#smistamento"

  get "users/customers" => "users#customers"

  get "users/labelers" => "users#labelers"

  
  resources :photos do 
    resources :questions 
  end

  resources :answers

  get "answers/question/:id" => "answers#nuova"

  #resources :users [:show, :update, :destroy]
  resources :users, only: [:index, :show, :destroy]


  match "*path", :to => "errors#internal_server_error", :via => :all

end

app/models/question.rb
class Question < ApplicationRecord
    belongs_to :photo, inverse_of: :questions
    has_many :answers,  inverse_of: :question

    #scope :owner, -> { joins(:photo).where(photo: { id: nil }) }
    # select(:user_id).joins(:photo)

    #scope :owner, -> {Question.select(:"photos.user_id").joins(:photo)}
    def count_answer()
        Answer.where(question_id: self.id).count
    end

    def count_answer1()
        Answer.where(question_id: self.id).where(answer: 1).count
    end

    def count_answer2()
        Answer.where(question_id: self.id).where(answer: 2).count
    end
    

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    before_action :authenticate_user!
    #before_action :check_photos
  # GET photos/:id/questions
  # GET photos/:id/questions.json
  def index
    @question = Question.new(photo_id: params[:photo_id])
    
    begin
      authorize! :read, @question, :message => "BEWARE: You are not authorized to read a photo."
    rescue CanCan::AccessDenied
      render "static/accessdenied" , status: 403
      return
    end

    redirect_to photo_path(params[:photo_id])
    
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    begin  
      id = params[:id] 
      @question=Question.find(id)
      @question.photo_id=params[:photo_id]
      begin
        authorize! :read, @question, :message => "BEWARE: You are not authorized to read a photo."
      rescue CanCan::AccessDenied
        render "static/accessdenied" , status: 403
        return
      end

    rescue ActiveRecord::RecordNotFound 
      render "static/notfound" , status: 404
      return
    end

  end

  # GET /questions/new
  def new
    @question = Question.new(photo_id: params[:photo_id])
    
    begin
      authorize! :create, @question, :message => "BEWARE: You are not authorized to create a photo."
    rescue CanCan::AccessDenied
      #render html: "ACCESSO NEGATO" , status: 403
      render "static/accessdenied" , status: 403
      return
    end
  end

  # POST /questions
  # POST /questions.json
  def create
    @parameter=params[:question].permit(:question_text, :question_answer1, :question_answer2, :correct)
    if @parameter[:correct] == '1'
      @parameter[:correct]=1
    else
      if @parameter[:correct] == '2'
        @parameter[:correct]=2
      else
        @parameter[:correct]=nil
      end
    end


    @parameter[:photo_id]=params[:photo_id]
    @question = Question.new(@parameter)

    begin
      authorize! :create, @question, :message => "BEWARE: You are not authorized to create a photo."
    rescue CanCan::AccessDenied
      render "static/accessdenied" , status: 403
      return
    end
    
    respond_to do |format|
      if @question.save
        format.html { redirect_to photo_path(params[:photo_id]), notice: 'Question was successfully created.' }
      else
        format.html { render :new }
      end
    end

  end


  # GET /questions/1/edit
  def edit
    begin  
      id = params[:id] 
      @question=Question.find(id)
      begin
        authorize! :update, @question, :message => "BEWARE: You are not authorized to update a photo."
      rescue CanCan::AccessDenied
        render "static/accessdenied" , status: 403
        return
      end

    rescue ActiveRecord::RecordNotFound 
      render "static/notfound" , status: 404
      return
    end
  end



  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    begin  
      id = params[:id] 
      @question=Question.find(id)
      begin
        authorize! :update, @question, :message => "BEWARE: You are not authorized to update a photo."
      rescue CanCan::AccessDenied
        render "static/accessdenied" , status: 403
        return
      end
    rescue ActiveRecord::RecordNotFound 
      render "static/notfound" , status: 404
      return
    end

    @parameter=question_params
    if @parameter[:correct] == '1'
      @parameter[:correct]=1
    else
      if @parameter[:correct] == '2'
        @parameter[:correct]=2
      else
        @parameter[:correct]=nil
      end
    end

    respond_to do |format|
      if @question.update(@parameter)
        format.html { redirect_to photo_question_path(params[:photo_id],@question), notice: 'Question was successfully updated.' }
      else
        format.html { render :edit }
      end
    end

  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    begin  
      id = params[:id] 
      @question=Question.find(id)
      begin
        authorize! :delete, @question, :message => "BEWARE: You are not authorized to destroy a photo."
      rescue CanCan::AccessDenied
        render "static/accessdenied" , status: 403
        return
      end
    rescue ActiveRecord::RecordNotFound 
      render "static/notfound" , status: 404
      return
    end

    @question.destroy
    respond_to do |format|
      format.html { redirect_to photo_path(params[:photo_id]), notice: 'Question was successfully destroyed.' }
    end
  end

  private


    def check_photos
      begin
        id = params[:photo_id] # retrieve photo ID from URI route
        @photo=Photo.find(id)
      rescue ActiveRecord::RecordNotFound 
        render "static/notfound" , status: 404
        return
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_question
      begin
        @question = Question.find(params[:id])
      rescue ActiveRecord::RecordNotFound 
        render "static/notfound" , status: 404
        return
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:photo_id, :question_text,:question_answer1,:question_answer2, :correct)
      #params.permit(:photo_id, :question_text)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_with(model: question, url: url, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :question_text %>
    <%= form.text_field :question_text, id: :question_question_text ,size:30,maxlength: 100%>
  </div>

  <div class="field">
    <%= form.label :question_answer1 %>
    <%= form.text_field :question_answer1, id: :question_question_answer1 ,size:30, maxlength: 50%>
  </div>

  <div class="field">
    <%= form.label :question_answer2 %>
    <%= form.text_field :question_answer2, id: :question_question_answer2, size:30,maxlength:50%>
  </div>

  <% if current_user.has_role? :admin %>
      <b>Correct Answer</b><br />
      <%if params[:id]==nil%>
        <%# SONO SU NEW %>
        
        <%= form.radio_button :correct, '1', :checked => true %> First<br />
        <%= form.radio_button :correct, '2' %> Second<br/>
      <%else%>  
          <%# SONO SU EDIT %>
          <%if question.correct!=nil %>
            <%if question.correct==1 %>
              <%= form.radio_button :correct, '1', :checked => true %> First<br />
              <%= form.radio_button :correct, '2' %> Second<br/>
            <%else%>
              <%= form.radio_button :correct, '1' %> First<br />
              <%= form.radio_button :correct, '2', :checked => true %> Second<br/>
            <%end%>
          <%else%>
            <%= form.radio_button :correct, '1', :checked => true %> First<br />
            <%= form.radio_button :correct, '2' %> Second<br/>
          <%end%>        
    <%end%>
    
  <%end%>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Edit Question</h1>

<% @photo=Photo.find(@question.photo_id)%>

<h4>
<%= link_to 'New Question', new_photo_question_path(params[:photo_id]) %> | 
<%= link_to 'Show Question', photo_question_path(params[:photo_id],@question) %> |
<%= link_to 'Destroy Question', photo_question_path(params[:photo_id],@question) , method: :delete, data: { confirm: 'Are you sure?' } %> | 
<%= link_to 'Back', photo_path(@photo) %>
</h4>

<% if @photo.url != nil %>
  <%= image_tag(@photo.url, alt: 'Image') if @photo.url %>
<% else %>
  <%= image_tag(@photo.image.url, alt: 'Image') if @photo.image? %>
<%end%>
<%if current_user.has_role? :admin%>
  <strong><%= link_to User.find(@photo.user_id).email, user_path(User.find(@photo.user_id))%></strong>
<%end%>

<h4>
<%= render 'form', question: @question, url: photo_question_path(params[:photo_id],@question) %>
</h4>

app/views/questions/index.html.erb
<h1>questions</h1>

<table>
  <thead>
    <tr>
      <th>Photo_id</th>
      <th>question_text</th>
      <th>question_answer1</th>
      <th>question_answer2</th>

      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <% if can? :manage, question%>
      <tr>
        <td><%= question.photo_id %></td>
        <td><%= question.question_text %></td>
        <td><%= question.question_answer1 %></td>
        <td><%= question.question_answer2 %></td>
        <td><%= link_to 'Show', photo_question_path(params[:photo_id],question) %></td>
        <td><%= link_to 'Edit', edit_photo_question_path(params[:photo_id],question) %></td>
        <td><%= link_to 'Destroy', photo_question_path(params[:photo_id],question), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>  
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New question', new_photo_question_path %>
<%= link_to 'QQuestion', photo_questions_path %>

app/views/questions/new.html.erb
<h1>New question</h1>

<% @photo=Photo.find(@question.photo_id)%>

<h4>
<%= link_to 'Back', photo_path(@photo) %>
</h4>


<% if @photo.url != nil %>
  <%= image_tag(@photo.url, alt: 'Image') if @photo.url %>
<% else %>
  <%= image_tag(@photo.image.url, alt: 'Image') if @photo.image? %>
<%end%>
<%if current_user.has_role? :admin%>
  <strong><%= link_to User.find(@photo.user_id).email, user_path(User.find(@photo.user_id))%></strong>
<%end%>

<h3>
<%= render 'form', question: @question , url: photo_questions_path %>
</h3>

app/views/questions/show.html.erb
<% @photo=Photo.find(@question.photo_id)%>
<h4>
<%= link_to 'New Question', new_photo_question_path(params[:photo_id]) %> | 
<%= link_to 'Edit Question', edit_photo_question_path(params[:photo_id],@question) %> |
<%= link_to 'Destroy Question', photo_question_path(params[:photo_id],@question) , method: :delete, data: { confirm: 'Are you sure?' } %> | 
<%= link_to 'Back', photo_path(@photo) %>
</h4>

<% if @photo.url != nil %>
  <%= image_tag(@photo.url, alt: 'Image') if @photo.url %>
<% else %>
  <%= image_tag(@photo.image.url, alt: 'Image') if @photo.image? %>
<%end%>
<%if current_user.has_role? :admin%>
  <strong><%= link_to User.find(@photo.user_id).email, user_path(User.find(@photo.user_id))%></strong>
<%end%>

<%count1=@question.count_answer1%>
<%count2=@question.count_answer2%>

  <h3><%= @question.question_text %></h3>
  <ul>
  <%if count1>count2%>
    <li><strong><span id="winner"><%= @question.question_answer1 %></strong> (Num Answer: <%=@question.count_answer1%>)</span></li>
    <li><strong><span id="loser"><%= @question.question_answer2 %></strong> (Num Answer: <%=@question.count_answer2%>)</span></li>
  <%else%>
    <%if count2>count1%>
      <li><strong><span id="loser"><%= @question.question_answer1 %></strong> (Num Answer: <%=@question.count_answer1%>)</span></li>
      <li><strong><span id="winner"><%= @question.question_answer2 %></strong> (Num Answer: <%=@question.count_answer2%>)</span></li>
    <%else%>
      <li><strong><span id="draw"><%= @question.question_answer1 %></strong> (Num Answer: <%=@question.count_answer1%>)</span></li>
      <li><strong><span id="draw"><%= @question.question_answer2 %></strong> (Num Answer: <%=@question.count_answer2%>)</span></li>
    <%end%>
  <%end%>
  </ul>

<%if current_user.has_role? :admin%>

    <h3><strong><%= link_to "Link to Answer", "/answers/question/#{@question.id}"%></strong></h3>


    <h3>Correct Answer:<strong>
    <%if @question.correct!=nil %>
      <%if @question.correct==1 %>
      <%=@question.question_answer1%>
      <%else%>
      <%=@question.question_answer2%>
      <%end%>
    <%end%>
    </strong></h3>
    
  <% @answers=Answer.where(question_id: @question.id)%>
  
  <h3>Question's Answer</h3>
  <% @answers.each do |answer|%>
    <h4>
    <%if answer.answer==2%>
      <%= link_to @question.question_answer2, answer_path(answer)%>
    <%else%>
      <%= link_to @question.question_answer1, answer_path(answer)%>
    <%end%>
    <strong><%= link_to User.find(answer.user_id).email, user_path(User.find(answer.user_id))%></strong>
    </h4><br>
  <%end%>
<%end%>