config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations",
                                       :omniauth_callbacks => "users/omniauth_callbacks"}
  #devise_for :users


  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #get ('/login') => redirect(:login) 
  get ("/") => redirect("users")
  
  get "/home" => "users#smistamento"

  get "users/customers" => "users#customers"

  get "users/labelers" => "users#labelers"

  
  resources :photos do 
    resources :questions 
  end

  resources :answers

  get "answers/question/:id" => "answers#nuova"

  #resources :users [:show, :update, :destroy]
  resources :users, only: [:index, :show, :destroy]


  match "*path", :to => "errors#internal_server_error", :via => :all

end

app/models/user.rb
class User < ApplicationRecord


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  
  has_many :photos,  inverse_of: :user
  has_many :answers,  inverse_of: :user

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  ROLES = [:admin, :labeler, :customer]
  
  
  # def self.create_with_omniauth(auth)
  
  #   user = find_or_create_by(uid: auth['uid'], provider:  auth['provider'])
  #   user.email = "#{auth['uid']}@#{auth['provider']}.com"
  #   user.password = auth['uid']
  #   user.name = auth['info']['name']  
    
  #   if User.exists?(user)
  #     user
  #   else
  #     user.save!
  #     user
  #   end
  # end



  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.roles_mask=2
      parse_name(user, auth.info.name)
    end
    
  end
  
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def roles= (roles)
    self.roles_mask = (roles & ROLES).map { |r| 2** ROLES.index(r) }.sum
  end

  def roles_int(roles)
    (roles & ROLES).map { |r| 2** ROLES.index(r) }.sum
  end
  
  def roles
    ROLES.reject { |r| ((roles_mask || 0) & 2** ROLES.index(r)).zero? }
  end
  
  def role_strings
    roles.map(& :to_s )
  end


  def has_role?(requested_role )
    roles.include?(requested_role)

  end

  def good_labeler?
    if self.has_role? :labeler
      @answers=Answer.where(user_id: self.id)
      @answers.each do |answer|
        @question=Question.find(answer.question_id)
        if @question.correct == nil
          puts "Salto"
          next
        end
        puts "valuto"
        if answer.answer != @question.correct
          return false
        end
      end
      return true
    else
      return false
    end
    
  end

  # def give_me_remain_answers
  #   query="select * from questions as q 
  #         where  q.id not in (select question_id 
  #                             from answers as a
  #                             where a.user_id=#{self.id})"

  #   @questions=@res=ActiveRecord::Base.connection.exec_query(query)
  # end

    

  private
  def self.parse_name(user, name)
    name_arr = name.split(" ")
    user.surname = name_arr.pop
    user.name = name_arr.join(" ")
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    
    def facebook
        # You need to implement the method below in your model (e.g. app/models/user.rb)
        @user = User.from_omniauth(request.env["omniauth.auth"])
        if @user.persisted?
            sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
            set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
        else
            session["devise.facebook_data"] = request.env["omniauth.auth"]
            redirect_to new_user_registration_url
        end
    end
    
    def failure
        redirect_to ("/")
    end

    private
  
    # def set_default_role
    #   self.roles = [:user]
    # end
    
    def self.parse_name(user, name)
      name_arr = name.split(" ")
      user.surname = name_arr.pop
      user.name = name_arr.join(" ")
    end
  
    # def set_num_likes_dislikes
    #   self.num_likes = 0
    #   self.num_dislikes = 0
    # end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :authenticate_user!


    
    def smistamento     
        if(current_user.has_role? :admin)
            redirect_to users_path
            return
        end

        if(current_user.has_role? :customer)
            redirect_to photos_path
            return
        end

        if(current_user.has_role? :labeler)
            redirect_to answers_path
            return
        end
    end


    def customers
        begin
            authorize! :manage, User, :message => "BEWARE: You are not authorized to manage a user."
        rescue CanCan::AccessDenied
            render "static/accessdenied" , status: 403
            return
        end
        @customers=User.where(roles_mask: 4)
    end

    def labelers
        begin
            authorize! :manage, User, :message => "BEWARE: You are not authorized to manage a user."
        rescue CanCan::AccessDenied
            render "static/accessdenied" , status: 403
            return
        end
        @labelers=User.where(roles_mask: 2)
    end
    
    
    def index
        begin
            authorize! :manage, User, :message => "BEWARE: You are not authorized to manage a user."
        rescue CanCan::AccessDenied
            render "static/accessdenied" , status: 403
            return
        end
        @photos=Photo.all()
    end
    

    def show
        begin
            id = params[:id] # retrieve user ID from URI route
            @user=User.find(id)
            begin
                authorize! :manage, User, :message => "BEWARE: You are not authorized to manage a user."
            rescue CanCan::AccessDenied
                render "static/accessdenied" , status: 403
                return
            end
        rescue ActiveRecord::RecordNotFound 
            render "static/notfound"
            flash[:warning] = "There is no user with that index"
            return
        end
    end


   


    # def edit
    #     begin
    #         id = params[:id] # retrieve user ID from URI route
    #         @user=User.find(id)
    #         begin
    #             authorize! :update, @user, :message => "BEWARE: You are not authorized to read a photo."
    #         rescue CanCan::AccessDenied
    #             #render html: "ACCESSO NEGATO" , status: 403
    #             render "static/accessdenied" , status: 403
    #         end
    #     rescue ActiveRecord::RecordNotFound 
    #         redirect_to :controller => "user", :action => "index"
    #         flash[:warning] = "There is no user with that index"
    #         return
    #     end
    #     redirect_to edit_user_registration_path
        
    # end

    # def update
    #     @user = User.find params[:id]
    #     # authorize! :update, @user, :message => "BEWARE: You are not authorized to update a user."
    #     # if current_user != @user.user
    #     #     flash[:warning] = "You are not authorized to update this user"
    #     #     redirect_to user_path(@user)
    #     # end
    #     # @user.update_attributes!(params[:user].permit(:name, :street, :address, :city, :telephone_number, :opening_time, :closing_time, :description, :notices, :icon))
    #     # respond_to do |client_wants|
    #     #     client_wants.html {
    #     #         flash[:notice] = "#{@user.name} was successfully updated."
    #     #         redirect_to user_path(@user)
    #     #     }
    #     #     client_wants.xml { render :xml => @user.to_xml }
    #     # end
    #     @user.update_attributes!(user_params_update)
    #     redirect_to user_path(@user)
    
    # end

    def destroy
        begin
            @user = User.find params[:id]
        rescue ActiveRecord::RecordNotFound 
            render "static/notfound" , status: 404
            return
        end

        begin
            authorize! :manage, User, :message => "BEWARE: You are not authorized to destroy a user."
        rescue CanCan::AccessDenied
            render "static/accessdenied" , status: 403
        end

        @user.destroy
        flash[:notice] = "User #{@user.id} deleted."
        redirect_to users_path
    end

    private 

    def set_user
        begin 
            @user = User.find(params[:id])
        rescue ActiveRecord::RecordNotFound 
            render "static/notfound" , status: 404
            return
        end
    end

    def user_params_create
        params[:user].permit(:name, :surname, :email, :password, :password_confirmation)
    end
    
    def user_params_update
        params[:place].permit(:name, :surname, :email, :password, :password_confirmation)
    end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :surname %>
    <%= form.text_field :surname, id: :user_surname %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/customers.html.erb
<h1>Customer's list</h2>
<h4><%= link_to 'Back', users_path %></h4>

<% @customers.each do |customer|%>
<h3>
<strong><%=customer.email%></strong>
<%= link_to 'View Customer', user_path(customer) %>
</h3>
<br>
<%end%>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>User</h1>

<h3>
<%= link_to 'Lista Labeler', "users/labelers" %>
<%= link_to 'Lista Customer', "users/customers" %>
<%= link_to 'Admin Profile', user_path(User.find(current_user.id))%>
</h3>


<h3>Batches</h3>
<% @photos.each do |photo|%>
    <%@user=User.find(photo.user_id)%>
    <%if photo.url!=nil%>
        <%= image_tag(photo.url, alt: 'Image', class: "img_list") if photo.url %>
    <%else%> 
        <%= image_tag(photo.image.url, alt: 'Image', class: "img_list") if photo.image? %>
    <%end%>
    <h4><%= link_to @user.email, user_path(@user) %> | <%= link_to "Show Photo", photo_path(photo) %></h4>
    <br>
<%end%>

app/views/users/labelers.html.erb
<h1>Labeler's list</h2>
<h4><%= link_to 'Back', users_path %></h4>

<% @labelers.each do |labeler|%>
<h3>
<strong><%=labeler.email%></strong>
<%= link_to 'View Labeler', user_path(labeler) %>==>
<%if labeler.good_labeler?%>
    He is reliable
<%else%>
    He isn't reliable
<%end%>
</h3>
<br>
<%end%>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h2><%=@user.role_strings[0].capitalize%></h2>
<h4>
name:<strong><%= @user.name %></strong><br>
surname:<strong><%= @user.surname %></strong><br>
email:<strong><%= @user.email %></strong><br>
<%= link_to 'Destroy User', user_path(@user), method: :delete, data: { confirm: 'Are you sure?' } %> | 
<%= link_to 'Back', users_path %>
</h4>

<% if @user.has_role? :customer or @user.has_role? :admin%>
  <% @photos=Photo.where(user_id: @user.id) %>
  <% @photos.each do |photo| %>
    <%if photo.url!=nil%>
      <%= image_tag(photo.url, alt: 'Image', class: "img_list") if photo.url %>
    <%else%> 
      <%= image_tag(photo.image.url, alt: 'Image', class: "img_list") if photo.image? %>
    <%end%>
    <h3><strong><%= link_to 'Show Photo', photo_path(photo) %>
  </strong></h3>
  <%end%>
<%end%>

<% if @user.has_role? :labeler %>
  <%@answers=Answer.where(user_id: @user.id)%>
  <% @answers.each do |answer| %>
    <% @question=Question.find(answer.question_id)%>
    <% @photo=Photo.find(@question.photo_id)%>
    <div class="img_with_text">
      <% if @photo.url != nil %>
        <%= image_tag(@photo.url, alt: 'Image', class: "img_list") if @photo.url %>
      <% else %>
        <%= image_tag(@photo.image.url, alt: 'Image', class: "img_list") if @photo.image? %>
      <%end%>

        <%= @question.question_text %><br>
        <%= link_to 'Show Answer', answer_path(answer) %>
      </div>
  <%end%>

<%end%>