config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations",
                                       :omniauth_callbacks => "users/omniauth_callbacks"}
  #devise_for :users


  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #get ('/login') => redirect(:login) 
  get ("/") => redirect("users")
  
  get "/home" => "users#smistamento"

  get "users/customers" => "users#customers"

  get "users/labelers" => "users#labelers"

  
  resources :photos do 
    resources :questions 
  end

  resources :answers

  get "answers/question/:id" => "answers#nuova"

  #resources :users [:show, :update, :destroy]
  resources :users, only: [:index, :show, :destroy]


  match "*path", :to => "errors#internal_server_error", :via => :all

end

app/models/answer.rb
class Answer < ApplicationRecord
    belongs_to :user,  inverse_of: :answers
    belongs_to :question,  inverse_of: :answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
    #before_action :set_answer, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!

    # GET /answers
    # GET /answers.json
    def index
        begin
            authorize! :read, Answer, :message => "BEWARE: You are not authorized to read a answer."
        rescue CanCan::AccessDenied
            render "static/accessdenied" , status: 403
            return
        end
        @answers = Answer.all
    end

    # GET /answers/1
    # GET /answers/1.json
    def show
        @answer = Answer.new(:id => params[:id], :user_id => current_user.id)
        
        begin
            @answer = Answer.find params[:id]
        rescue ActiveRecord::RecordNotFound 
            render "static/notfound" , status: 404
            return
        end

        begin
            authorize! :read, @answer, :message => "BEWARE: You are not authorized to read a answer."
        rescue CanCan::AccessDenied
            render "static/accessdenied" , status: 403
            return
        end

        
        
    end

    def nuova
        begin
            @question = Question.find params[:id]
        rescue ActiveRecord::RecordNotFound 
            render "static/notfound" , status: 404
            return
        end

        begin
            authorize! :manage, :all, :message => "BEWARE: You don't have the necessary requirements"
        rescue CanCan::AccessDenied
            render "static/accessdenied" , status: 403
            return
        end



        render :new


    end

    # GET /answers/new
    def new
        @answer = Answer.new(:user_id => current_user.id)
        begin
            authorize! :create, @answer, :message => "BEWARE: You are not authorized to read a answer."
        rescue CanCan::AccessDenied
            render "static/accessdenied" , status: 403
            return
        end

        if Question.all.empty?
            @question={}
        else
            @question=Question.order('RANDOM()').first
        end
    end

    # GET /answers/1/edit
    def edit
        @answer = Answer.new(:id => params[:id], :user_id => current_user.id)
        begin
            @answer = Answer.find params[:id]
        rescue ActiveRecord::RecordNotFound 
            render "static/notfound" , status: 404
            return
        end
        
        begin
            authorize! :update, @answer, :message => "BEWARE: You are not authorized to read a answer."
        rescue CanCan::AccessDenied
            render "static/accessdenied" , status: 403
            return
        end

        
    end

    # POST /answers
    # POST /answers.json
    def create
        @parameter=answer_params
        @parameter["user_id"]=current_user.id
        @answer=Answer.new(@parameter)
        begin
            authorize! :create, @answer, :message => "BEWARE: You are not authorized to create an answer."
        rescue CanCan::AccessDenied
            render "static/accessdenied" , status: 403
            return
        end

        respond_to do |format|
            if @answer.save
            format.html { redirect_to answers_path, notice: 'Answer was successfully created.' }
            #format.json { render :show, status: :created, location: @answer }
            else
            format.html { render :new }
            #format.json { render json: @answer.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /answers/1
    # PATCH/PUT /answers/1.json
    def update
        begin
            @answer = Answer.find params[:id]
        rescue ActiveRecord::RecordNotFound 
            render "static/notfound" , status: 404
            return
        end

        begin
            authorize! :update, @answer, :message => "BEWARE: You are not authorized to read a answer."
        rescue CanCan::AccessDenied
            render "static/accessdenied" , status: 403
            return
        end

        

        respond_to do |format|
            if @answer.update(answer_params)
                format.html { redirect_to answer_path(@answer), notice: 'Answer was successfully updated.' }
            else
                format.html { render :edit }
            end
        end
    end

    # DELETE /answers/1
    # DELETE /answers/1.json
    def destroy
        begin
            @answer = Answer.find params[:id]
        rescue ActiveRecord::RecordNotFound 
            render "static/notfound" , status: 404
            return
        end

        begin
            authorize! :update, @answer, :message => "BEWARE: You are not authorized to read a answer."
        rescue CanCan::AccessDenied
            render "static/accessdenied" , status: 403
            return
        end

        @answer.destroy
        respond_to do |format|
            format.html { redirect_to answers_path, notice: 'Answer was successfully destroyed.' }
        end
    end

    private
    
    def set_answer
        begin
            @answer = Answer.find(params[:id])
        rescue ActiveRecord::RecordNotFound 
            render "static/notfound" , status: 404
            return
        end
      end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
        params.require(:answer).permit(:answer,:question_id)
        #params.permit(:photo_id, :answer_text)
    end

    
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<%= form_with(model: answer, url: url, local: true) do |form| %>
  <% if answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= hidden_field(:answer, :question_id, value: params[:question_id]) %>
  
  

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :answer_user_id %>
  </div>

  <div class="field">
    <%= form.label :answer %>
    <%= form.text_field :answer, id: :answer_answer %>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing Answer</h1>


<% @question=Question.find(@answer.question_id)%>
<% @photo=Photo.find(@question.photo_id)%>

<h4>
<%= link_to 'New Answer', new_answer_path %> |
<%= link_to 'Show Answer', answer_path(@answer) %> |
<%= link_to 'Destroy Answer', answer_path(@answer) , method: :delete, data: { confirm: 'Are you sure?' } %>

<%= link_to 'Back', answers_path %>
</h4>


<%if @photo.url!=nil%>
  <%= image_tag(@photo.url, alt: 'Image') if @photo.url %>
<%else%> 
  <%= image_tag(@photo.image.url, alt: 'Image') if @photo.image? %>
<%end%>





<%= form_with(model:@answer , url: answer_path(@answer), local: true) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= hidden_field(:answer, :question_id, value: @question.id) %>

    <h3>
    <%= @question.question_text %>
  </h3>


    <h4>
    <%= f.radio_button :answer, '1', :checked => true %> <%= @question.question_answer1 %> <br />
    <%= f.radio_button :answer, '2' %> <%= @question.question_answer2%> <br />
    </h4>


    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>
<%if current_user.has_role? :admin%>
  Answered by:<strong><%= link_to User.find(@answer.user_id).email, user_path(User.find(@answer.user_id))%></strong><br>
<%end%>

app/views/answers/index.html.erb
<h1>answers</h1>
<%if Question.all.empty?%>
  <h4>There aren't any questions to answer</h4>
<%else%>
  <h4><%= link_to 'New answer', new_answer_path %></h4>
<%end%>
    <% @answers.each do |answer| %>
      <% if can? :manage, answer%>
      <div class="img_with_text">
      <% @question=Question.find(answer.question_id)%>
      <% @photo=Photo.find(@question.photo_id)%>
      <% if @photo.url != nil %>
        <%= image_tag(@photo.url, alt: 'Image', class: "img_list") if @photo.url %>
      <% else %>
        <%= image_tag(@photo.image.url, alt: 'Image', class: "img_list") if @photo.image? %>
      <%end%>
        <%if current_user.has_role? :admin%>
        <strong><%= link_to User.find(answer.user_id).email, user_path(answer.user)%></strong><br>
        <%end%>
        <%= @question.question_text %><br>
        <%= link_to 'Show', answer_path(answer) %>
        <%= link_to 'Edit', edit_answer_path(answer) %>
        <%= link_to 'Destroy', answer_path(answer), method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>

      
    <% end %>

    <% end %>
    </table>


<br>

app/views/answers/new.html.erb
<h1>New Answer</h1>

<% @photo=Photo.find(@question.photo_id)%>
<%@answer=Answer.new %>

<h4>
<%= link_to 'New Answer', new_answer_path %> |
<%= link_to 'Back', answers_path %>
</h4>


<%if @photo.url!=nil%>
  <%= image_tag(@photo.url, alt: 'Image') if @photo.url %>
<%else%> 
  <%= image_tag(@photo.image.url, alt: 'Image') if @photo.image? %>
<%end%>

<%if current_user.has_role? :admin %>
    <h4><%= link_to "Show Question", photo_question_path(@photo.id,@question.id)%></h4><br>
  <%end%>

<%= form_with(model:@answer , url: answers_path, local: true) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= hidden_field(:answer, :question_id, value: @question.id) %>

  <h3>
    <%= @question.question_text %>
  </h3>


    <h4>
    <%= f.radio_button :answer, '1', :checked => true %> <%= @question.question_answer1 %> <br />
    <%= f.radio_button :answer, '2' %> <%= @question.question_answer2%> <br />
    </h4>

    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>

app/views/answers/show.html.erb
<% @question=Question.find(@answer.question_id)%>
<% @photo=Photo.find(@question.photo_id)%>

<h4>
<%= link_to 'New Answer', new_answer_path %> |
<%= link_to 'Edit Answer', edit_answer_path(@answer) %> |
<%= link_to 'Destroy Answer', answer_path(@answer) , method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Back', answers_path %>
</h4>

<%if @photo.url!=nil%>
  <%= image_tag(@photo.url, alt: 'Image') if @photo.url %>
<%else%> 
  <%= image_tag(@photo.image.url, alt: 'Image') if @photo.image? %>
<%end%>


  <%if current_user.has_role? :admin%>
    <h4><%= link_to "Show Question", photo_question_path(@photo.id,@question.id)%></h4><br>
  <%end%>


  <h3><%= @question.question_text %></h3>

  <ul>
  <%if @answer.answer==1%>
    <li><strong><span id="winner"><%= @question.question_answer1 %></strong></span></li>
    <li><strong><span id="loser"><%= @question.question_answer2 %></strong></span></li>
  <%else%>
    <li><strong><span id="loser"><%= @question.question_answer1 %></strong></span></li>
    <li><strong><span id="winner"><%= @question.question_answer2 %></strong></span></li>
  <%end%>
  
  </ul>
<%if current_user.has_role? :admin%>
Answered by:<strong><%= link_to User.find(@answer.user_id).email, user_path(User.find(@answer.user_id))%></strong><br>
<%end%>